################################################################################################################################
#
# ███████╗░█████╗░██╗░░░██╗░█████╗░████████╗██╗░█████╗░███╗░░██╗██╗░░██╗░█████╗░██╗░░░██╗░██████╗███████╗██╗░░░██╗░░██╗██╗
# ╚════██║██╔══██╗██║░░░██║██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║██║░░██║██╔══██╗██║░░░██║██╔════╝██╔════╝██║░░░██║░██╔╝██║
# ░░███╔═╝███████║██║░░░██║██║░░╚═╝░░░██║░░░██║██║░░██║██╔██╗██║███████║██║░░██║██║░░░██║╚█████╗░█████╗░░╚██╗░██╔╝██╔╝░██║
# ██╔══╝░░██╔══██║██║░░░██║██║░░██╗░░░██║░░░██║██║░░██║██║╚████║██╔══██║██║░░██║██║░░░██║░╚═══██╗██╔══╝░░░╚████╔╝░███████║
# ███████╗██║░░██║╚██████╔╝╚█████╔╝░░░██║░░░██║╚█████╔╝██║░╚███║██║░░██║╚█████╔╝╚██████╔╝██████╔╝███████╗░░╚██╔╝░░╚════██║
# ╚══════╝╚═╝░░╚═╝░╚═════╝░░╚════╝░░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝╚═╝░░╚═╝░╚════╝░░╚═════╝░╚═════╝░╚══════╝░░░╚═╝░░░░░░░░╚═╝
#
#   Sponsor: https://minestrator.com/a/FAIRYSKY
#   Documentation: https://zauctionhouse.groupez.dev/
#   Discord: https://discord.groupez.dev/
#
################################################################################################################################

# Enables detailed logs and error messages in the console.
# If you need support, make sure to activate this option and check your console logs.
enable-debug: false

#
# - SQLITE
# - MARIADB
# - MYSQL
storage-type: SQLITE

# Database configuration.
# It is strongly recommended to use a database to store all plugin data.
database-configuration:
  # Prefix applied to all tables created by the plugin.
  # If you use the same database for multiple plugins, this helps avoid conflicts.
  # It is recommended not to change this value once the plugin is in use.
  table-prefix: "zauctionhouse_"
  # IP address of the machine hosting your database.
  host: 192.168.10.10
  # Port of your database server.
  # Default MySQL port: 3306
  port: 3306
  # Username used to log into the database.
  user: homestead
  # Password associated with the database user.
  password: 'secret'
  # Name of the database where data will be stored.
  database: zauctionhouse
  # Enables SQL debugging.
  # Activates verbose SQL logs, useful for identifying database issues.
  debug: false

# Vous permet de définir des clés qui seront remplacées par la couleur pour vos messages.
# Cela permet de simplifier la configuration de vos messages
message-colors:
  - key: "<primary>"
    color: "#24d65d"
  - key: "<secondary>"
    color: "#656665"
  - key: "<error>"
    color: "#ff0000"
  - key: "<success>"
    color: "#00ff00"

# Configuration des commandes, aliases, arguments
# Pour reload cette configuration, vous devez relancer votre serveur !
commands:
  # Commande principale, /zauctionhouse
  main-command:
    # Aliases de la commande principale
    aliases:
      - "ah"
      - "hdv"
      - "auction"
      - "zauction"

  # Commande de vente /zauctionhouse sell
  sell:
    aliases:
      - "sell"
      - "s"
      - "vendre"
    arguments:
      - name: "price"
        required: true
        auto-completion:
          - 1000
          - 10000
          - 25000
      - name: "amount"
        required: false
        auto-completion:
          - '1'
          - '%max-stack-size%'
      - name: "economy"
        required: false
        auto-completion:
          - "vault"
